WIP utiliser les données de data.culture.gouv.fr pour la synchro des objets
betagouv/collectif-objets pull request #1153
Opened 2024-02-01 10:55 UTC by adipasquale

2024-02-13 13:38 UTC, bricedurand commented on app/jobs/synchronizer/objets/revision_edifice_concern.rb
> +        elsif existing_edifice_by_ref && existing_edifice_by_ref.code_insee != palissy_INSEE
Autre option à considérer : ne pas importer l'objet car il est dans un état incertain

2024-02-13 13:55 UTC, bricedurand commented on spec/jobs/synchronizer/objets/row_spec.rb
> +  describe "classé/déclassé" do
Je suis allé voir dans sur data.culture.gouv.fr et le champ `typologie_de_la_protection` a toujours les même valeurs qu'avant (cf le test dans `objet_spec`).

Entre temps la MPP a d'ailleurs corrigé quelques valeurs incohérentes du type "fleur" ou "devenu non protégé", mais il en reste encore. 

Dans 95% des cas le champ vaut "classé au titre objet" ou "inscrit au titre objet", donc à part quelques exceptions ce champ me paraît toujours exploitable.

2024-02-13 14:03 UTC, bricedurand requested changes
La structure est bien même si ce n'est pas toujours évident de comprendre le rôle de chaque classe. Ça mériterait quelques commentaires dans Batch, Row, Eagerload et Revision.


Peux-tu repartir sur le champ `typologie_de_protection` pour déterminer si l'objet est classé ou non ?

Je suis allé voir dans sur data.culture.gouv.fr et le champ typologie_de_la_protection a toujours les mêmes valeurs qu'avant (cf le test dans objet_spec).

Dans 95% des cas le champ vaut "classé au titre objet" ou "inscrit au titre objet", donc à part quelques exceptions ce champ me paraît toujours exploitable (et la MPP corrige les exceptions au fil du temps).

2024-02-13 14:36 UTC, adipasquale commented
merci d’avoir relu ce gros morceau en détail @bricedurand  🙇 

et merci d’être allé vérifier le contenu du CSV. en effet il reste des données dans la colonne `Typologie_de_la_protection` (`PROT`) . Cependant ce ne sont pas les "bonnes" ou du moins pas les mêmes qu’avant. La colonne `Date_et_typologie_de_la_protection` (`DPRO`) contient plus d’informations, dont celle qui nous intéresse.

La règle d’import actuellement appliquée sur `main` à ce sujet est très simple et conservative : 

`and ("PROT" IS NULL OR "PROT" != 'déclassé')` cf [api_client_sql.rb](https://github.com/betagouv/collectif-objets/blob/main/app/jobs/synchronizer/api_client_sql.rb#L34)

Or il n’y a plus aucune occurence du mot `déclassé` dans cette colonne. Ce mot apparait en revanche 677 fois dans la colonne `Date_et_typologie_de_la_protection` : 

![Screenshot 2024-02-13 at 15 16 15](https://github.com/betagouv/collectif-objets/assets/883348/bc54e3ec-cb33-482b-b9f9-2e13ac1008cc)

J’ai aussi fait un export des lignes du CSV où `Date_et_typologie_de_la_protection` est rempli mais pas `Typologie_de_la_protection`, il y en a environ 1000, tu peux les voir sur [ce premier gist](https://gist.github.com/adipasquale/ca3b796004bbeab54be278c975f18bc8)

Pour voir dans l’autre sens s’il y aurait de la donnée dans `Typologie_de_la_protection` qui n’est pas dans `Date_et_typologie_de_la_protection` c’est plus compliqué. J’ai d’abord vérifié que `Date_et_typologie_de_la_protection` est toujours rempli quand `PROT` est rempli. Ensuite j’ai fait une vérification visuelle rapide des 13k lignes où `Typologie_de_la_protection` est rempli et j’ai l’impression que l’info est toujours la même ou plus détaillée dans `Date_et_typologie_de_la_protection`. Tu peux voir l’export de ces 13k lignes [dans ce second gist](https://gist.github.com/adipasquale/b45986577d73ad1b5e88d164e346e20c)

à mon avis, il vaut donc mieux utiliser `Date_et_typologie_de_la_protection` que `Typologie_de_la_protection`.

2024-02-13 16:49 UTC, adipasquale commented on app/jobs/synchronizer/objets/revision_edifice_concern.rb
> +        elsif existing_edifice_by_ref && existing_edifice_by_ref.code_insee != palissy_INSEE
en effet, bien vu ! 

est-ce que tu as une préférence forte dans un sens ou dans l’autre ? les deux me vont, j’ai une préférence modérée pour ce qu’il y a actuellement car ça évite un peu de boulot mais je peux changer sans problème, ça prendra pas très longtemps.

2024-02-14 09:39 UTC, adipasquale commented
@bricedurand j’ai rajouté un commentaire sur xsv et déplacé la condition sur la présence du code INSEE du EdificeConcern vers le row, c’est mieux 👍 merci. https://github.com/betagouv/collectif-objets/pull/1153/commits/899375300b56322878a821fd2c5407520b53b373

Je déploie 🚀

2024-02-14 09:40 UTC, merged