Évolution de la vue d'un département côté conservateur
betagouv/collectif-objets pull request #978
Opened 2023-08-25 12:03 UTC by bricedurand

L'objectif est de faire évoluer la page de visualisation d'un département côté conservateur (/conservateurs/departements/ID_DU_DEPARTEMENT), et plus précisément le tableau des communes, qui ressemble actuellement à ça :

![Vue_Departement avant](https://github.com/betagouv/collectif-objets/assets/1522772/5dbbbfd8-0360-4cad-8b8d-0bb73a3b65b7)

Voici la maquette vers laquelle je dois aller :
![Vue_Departement objectif](https://github.com/betagouv/collectif-objets/assets/1522772/4edf12f8-5009-4253-b463-661304840dfe)

Dans la colonne Objets prioritaires, il y a désormais une distinction entre les objets "disparus" et les objets "en péril" (en très mauvais état). Un objet est dit "prioritaire" s'il est disparu ou en péril.

Le tri de la colonne Objets prioritaires se fait en fonction du nombre total d'objets prioritaires.
Le filtre d'objets prioritaires (via la select box en haut du tableau) permet de ne remonter que les communes ayant au moins un objet prioritaire du critère choisi (disparu ou en péril).

2023-08-25 13:10 UTC, freesteph reviewed
Désolé que des nitpicks sur les trucs pas importants, le SQL est trop complexe (légitimement complexe) pour que j'y trouve des choses.

Il y a une batterie de tests (e2e?) qui couvrent tes changements ? C'est sûrement le meilleur moyen de se rassurer dans ce genre de chantiers.

2023-08-25 13:10 UTC, freesteph commented on app/views/conservateurs/departements/_communes_search.html.haml
> +                    - if commune.en_peril_count.positive?
au lieu d'utiliser les formes `positive?` j'aurais plus fait `commune.en_peril.any?` pour une meilleure lecture

2023-08-25 13:10 UTC, freesteph commented on app/helpers/dossier_helper.rb
> +    color = ""
Pour éviter les embranchements logiques :  

```yml
  dossier:
    status_badge:
      construction: Partiellement recensé
      submitted: Non analysé
      accepted: Analysé
      none: Non recensé
```

```rb
status = dossier&.status || "none"

    color = {
      construction: "new",
      submitted: "info",
      accepted: "success",
      none: ""
    }[status.to_sym]
    content_tag(
      "p",
      t("dossier.status_badge.#{status}"),
      class: "fr-badge fr-badge--#{color} #{small ? 'fr-badge--sm' : ''}"
    )

2023-08-25 13:12 UTC, bricedurand commented
@Samuelfaure avec plaisir pour tes commentaires

2023-08-25 13:18 UTC, bricedurand commented
> Désolé que des nitpicks sur les trucs pas importants, le SQL est trop complexe (légitimement complexe) pour que j'y trouve des choses.
> 
> Il y a une batterie de tests (e2e?) qui couvrent tes changements ? C'est sûrement le meilleur moyen de se rassurer dans ce genre de chantiers.

Merci pour ces retours !
Pas vraiment de tests pour le moments, il en faudrait au moins pour vérifier les données remontées.

2023-08-25 13:24 UTC, bricedurand commented on app/views/conservateurs/departements/_communes_search.html.haml
> +                    - if commune.en_peril_count.positive?
Oui en effet c'est plus lisible comme ça.
J'ai fait ce choix car le compteur en_peril_count est déjà là, alors que utiliser commune.en_peril.any? va lancer une nouvelle requête.

Sinon on pourrait avoir une méthode dans ce genre :
```ruby
class Commune
  def a_des_objets_en_peril?
    en_peril_count.positive?
  end
```

2023-08-25 13:31 UTC, Samuelfaure reviewed
Petites remarques, rien de méchant, par contre les énormes requêtes SQL me trigger quelque peu, ça ressemble à de la dette technique qu'il faudrait migrer en ActiveRecord autant que possible

2023-08-25 13:31 UTC, Samuelfaure commented on app/models/commune.rb
> +  def self.ransackable_associations(_ = nil) = %w[dossier dossiers objets]
je vois pas l'interêt d'avoir un param par défaut qu'on utilise pas, mais peut-être que @freesteph saura pourquoi

2023-08-25 13:31 UTC, Samuelfaure commented on app/views/conservateurs/departements/_communes_search.html.haml
> +        = f.select :dossier_status_eq, Dossier.aasm.states_for_select.prepend(["Sélectionnez une option", ""]), {}, data: { controller: "input-autosubmit", action: "input-autosubmit#submit" }
en général on évite de chainer les méthodes dans les views (i.e `Dossier.aasm.states_for_select`) on préfère utiliser des variables d'instance, helpers ou façades

Ici peut-être un helper:

```ruby
def aasm_dossiers_states
  Dossier.aasm.states_for_select.prepend(["Sélectionnez une option", ""])
end
```

2023-08-25 13:32 UTC, freesteph commented on app/views/conservateurs/departements/_communes_search.html.haml
> +                    - if commune.en_peril_count.positive?
non bah évitons la requête alors, j'ai pas trouvé d'identifiant `en_peril_count` dans le code donc je pensais que ça lancerait une requête aussi.

Rubocop insiste pour que j'utilise `.positive?` quand je fais des comparaisons avec zéro dont la sémantique est plus "est-ce qu'il y en a ?" plutôt que "est-ce que ce chiffre est positif ?" mais bon on survivra hein

2023-08-25 14:40 UTC, bricedurand commented on app/models/commune.rb
> +  def self.ransackable_associations(_ = nil) = %w[dossier dossiers objets]
C'est parce qu'il s'agit d'une méthode venant d'une lib, et qu'elle prend un paramètre. Je crois que si on l'enlève ça ne fonctionne plus

2023-08-28 13:28 UTC, Samuelfaure approved these changes

2023-08-28 14:53 UTC, Samuelfaure requested changes

2023-08-28 14:53 UTC, Samuelfaure commented on spec/models/commune_spec.rb
> +  end
Je dois avouer les titres de spec en français ça me choque

2023-08-28 14:53 UTC, Samuelfaure commented on spec/models/commune_spec.rb
> +    end
Inutile je pense, le test suivant vérifie ça aussi

2023-08-28 14:53 UTC, Samuelfaure commented on spec/models/commune_spec.rb
> +      commune = create(:commune)
let(:commune) { create(:commune) }

2023-08-28 14:53 UTC, Samuelfaure commented on spec/models/commune_spec.rb
> +      commune = create(:commune)
```suggestion
      let(:commune) { create(:commune) }
```

2023-08-28 14:53 UTC, Samuelfaure commented on spec/models/commune_spec.rb
> +  end
(après je demande pas nécessairement de changer ici)

2023-09-04 08:05 UTC, merged

2023-11-07 14:37 UTC, bricedurand commented
> Petites remarques, rien de méchant, par contre les énormes requêtes SQL me trigger quelque peu, ça ressemble à de la dette technique qu'il faudrait migrer en ActiveRecord autant que possible

@Samuelfaure En rediscutant de cette PR avec quelqu'un, je me suis rendu compte que je n'avais pas vu ton commentaire. Les énormes requêtes SQL étaient la raison principale pour laquelle j'avais sollicité une review :)

Je ne vois pas comment faire mieux, à part en ajoutant des champs pré-calculés. Par exemple un counter cache recensements_analysed_count sur la table dossiers, qui évite cette jointure :
```SQL
LEFT OUTER JOIN (
  SELECT dossiers.id, 
    SUM(CASE WHEN recensements.analysed_at IS NOT NULL THEN 1 ELSE 0 END) AS recensements_analysed_count
  FROM dossiers
  LEFT OUTER JOIN recensements
  ON dossiers.id = recensements.dossier_id
  GROUP BY dossiers.id
  ) AS nb_recensements_par_dossiers
```